version: '3.4'

services:
  SqlServerDb:
        container_name: SqlServerContainer
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
            - 8002:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=myStong_Password123# 
  sotags:
    image: ${DOCKER_REGISTRY-}sotags
    ports:
      - "9000:8080"
      - "9001:8081"
    environment:
      - ASPNETCORE_HTTPS_PORT=8081
    build:
      context: SOTags
      dockerfile: Dockerfile
    depends_on:
    - SqlServerDb
